In [3]:
import pandas as pd
import numpy as np
df=pd.read_csv('auto-mpg.csv')
print(df)

      mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0
1    15.0          8         350.0        165    3693          11.5
2    18.0          8         318.0        150    3436          11.0
3    16.0          8         304.0        150    3433          12.0
4    17.0          8         302.0        140    3449          10.5
..    ...        ...           ...        ...     ...           ...
393  27.0          4         140.0         86    2790          15.6
394  44.0          4          97.0         52    2130          24.6
395  32.0          4         135.0         84    2295          11.6
396  28.0          4         120.0         79    2625          18.6
397  31.0          4         119.0         82    2720          19.4

     model year  origin                   car name
0            70       1  chevrolet chevelle malibu
1            70       1          buick skylark 320
2            70       1         plymouth satellite
3            70       1              amc rebel sst
4            70       1                ford torino
..          ...     ...                        ...
393          82       1            ford mustang gl
394          82       2                  vw pickup
395          82       1              dodge rampage
396          82       1                ford ranger
397          82       1                 chevy s-10

[398 rows x 9 columns]

In [5]:
print("DataFrame")
print(df)
print("Shape of df")
print(df.shape)
print("Size of df")
print(df.size)
print("Size of columns")
print(df.columns)
print("df.info")
print(df.info())

DataFrame
      mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0
1    15.0          8         350.0        165    3693          11.5
2    18.0          8         318.0        150    3436          11.0
3    16.0          8         304.0        150    3433          12.0
4    17.0          8         302.0        140    3449          10.5
..    ...        ...           ...        ...     ...           ...
393  27.0          4         140.0         86    2790          15.6
394  44.0          4          97.0         52    2130          24.6
395  32.0          4         135.0         84    2295          11.6
396  28.0          4         120.0         79    2625          18.6
397  31.0          4         119.0         82    2720          19.4

     model year  origin                   car name
0            70       1  chevrolet chevelle malibu
1            70       1          buick skylark 320
2            70       1         plymouth satellite
3            70       1              amc rebel sst
4            70       1                ford torino
..          ...     ...                        ...
393          82       1            ford mustang gl
394          82       2                  vw pickup
395          82       1              dodge rampage
396          82       1                ford ranger
397          82       1                 chevy s-10

[398 rows x 9 columns]
Shape of df
(398, 9)
Size of df
3582
Size of columns
Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin', 'car name'],
      dtype='object')
df.info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB
None

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

In [7]:
print("To get required data from from top of the data")
df.head(10)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
5,15.0,8,429.0,198,4341,10.0,70,1,ford galaxie 500
6,14.0,8,454.0,220,4354,9.0,70,1,chevrolet impala
7,14.0,8,440.0,215,4312,8.5,70,1,plymouth fury iii
8,14.0,8,455.0,225,4425,10.0,70,1,pontiac catalina
9,15.0,8,390.0,190,3850,8.5,70,1,amc ambassador dpl

In [8]:
print("To get required data from from bottom of the data")
df.tail(10)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
388,26.0,4,156.0,92,2585,14.5,82,1,chrysler lebaron medallion
389,22.0,6,232.0,112,2835,14.7,82,1,ford granada l
390,32.0,4,144.0,96,2665,13.9,82,3,toyota celica gt
391,36.0,4,135.0,84,2370,13.0,82,1,dodge charger 2.2
392,27.0,4,151.0,90,2950,17.3,82,1,chevrolet camaro
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [10]:
print("To print random 3 values")
df.sample(3)

To print random 3 values

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
51,30.0,4,79.0,70,2074,19.5,71,2,peugeot 304
272,23.8,4,151.0,85,2855,17.6,78,1,oldsmobile starfire sx
311,32.1,4,98.0,70,2120,15.5,80,1,chevrolet chevette

In [11]:
df.values

array([[18.0, 8, 307.0, ..., 70, 1, 'chevrolet chevelle malibu'],
       [15.0, 8, 350.0, ..., 70, 1, 'buick skylark 320'],
       [18.0, 8, 318.0, ..., 70, 1, 'plymouth satellite'],
       ...,
       [32.0, 4, 135.0, ..., 82, 1, 'dodge rampage'],
       [28.0, 4, 120.0, ..., 82, 1, 'ford ranger'],
       [31.0, 4, 119.0, ..., 82, 1, 'chevy s-10']], dtype=object)

In [12]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight            int64
acceleration    float64
model year        int64
origin            int64
car name         object
dtype: object

In [22]:
print("Describe method ")
print(df.describe())#gives float 
print("--------------------------------------------------------------")
print("Including Object in describe method")
print(df.describe(include='object'))

Describe method
              mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000
mean    23.514573    5.454774    193.425879  2970.424623     15.568090
std      7.815984    1.701004    104.269838   846.841774      2.757689
min      9.000000    3.000000     68.000000  1613.000000      8.000000
25%     17.500000    4.000000    104.250000  2223.750000     13.825000
50%     23.000000    4.000000    148.500000  2803.500000     15.500000
75%     29.000000    8.000000    262.000000  3608.000000     17.175000
max     46.600000    8.000000    455.000000  5140.000000     24.800000

       model year      origin
count  398.000000  398.000000
mean    76.010050    1.572864
std      3.697627    0.802055
min     70.000000    1.000000
25%     73.000000    1.000000
50%     76.000000    1.000000
75%     79.000000    2.000000
max     82.000000    3.000000
--------------------------------------------------------------
Including Object in describe method
       horsepower    car name
count         398         398
unique         94         305
top           150  ford pinto
freq           22           6

In [20]:
print("----------------------------------------------------------")
print("It will include all the object and numeric")
df.describe(include="all")

----------------------------------------------------------
It will include all the object and numeric

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
count,398.000000,398.000000,398.000000,398,398.000000,398.000000,398.000000,398.000000,398
unique,NaN,NaN,NaN,94,NaN,NaN,NaN,NaN,305
top,NaN,NaN,NaN,150,NaN,NaN,NaN,NaN,ford pinto
freq,NaN,NaN,NaN,22,NaN,NaN,NaN,NaN,6
mean,23.514573,5.454774,193.425879,NaN,2970.424623,15.568090,76.010050,1.572864,NaN
std,7.815984,1.701004,104.269838,NaN,846.841774,2.757689,3.697627,0.802055,NaN
min,9.000000,3.000000,68.000000,NaN,1613.000000,8.000000,70.000000,1.000000,NaN
25%,17.500000,4.000000,104.250000,NaN,2223.750000,13.825000,73.000000,1.000000,NaN
50%,23.000000,4.000000,148.500000,NaN,2803.500000,15.500000,76.000000,1.000000,NaN
75%,29.000000,8.000000,262.000000,NaN,3608.000000,17.175000,79.000000,2.000000,NaN
max,46.600000,8.000000,455.000000,NaN,5140.000000,24.800000,82.000000,3.000000,NaN

In [24]:
df.describe(include=['int64','float'])
df.describe(exclude='int64')

               mpg  displacement horsepower  acceleration    car name
count   398.000000    398.000000        398    398.000000         398
unique         NaN           NaN         94           NaN         305
top            NaN           NaN        150           NaN  ford pinto
freq           NaN           NaN         22           NaN           6
mean     23.514573    193.425879        NaN     15.568090         NaN
std       7.815984    104.269838        NaN      2.757689         NaN
min       9.000000     68.000000        NaN      8.000000         NaN
25%      17.500000    104.250000        NaN     13.825000         NaN
50%      23.000000    148.500000        NaN     15.500000         NaN
75%      29.000000    262.000000        NaN     17.175000         NaN
max      46.600000    455.000000        NaN     24.800000         NaN

In [25]:
df.nunique()#gives count of column

mpg             129
cylinders         5
displacement     82
horsepower       94
weight          351
acceleration     95
model year       13
origin            3
car name        305
dtype: int64

In [27]:
print("to print unique car names")
df['car name'].unique()

array(['chevrolet chevelle malibu', 'buick skylark 320',
       'plymouth satellite', 'amc rebel sst', 'ford torino',
       'ford galaxie 500', 'chevrolet impala', 'plymouth fury iii',
       'pontiac catalina', 'amc ambassador dpl', 'dodge challenger se',
       "plymouth 'cuda 340", 'chevrolet monte carlo',
       'buick estate wagon (sw)', 'toyota corona mark ii',
       'plymouth duster', 'amc hornet', 'ford maverick', 'datsun pl510',
       'volkswagen 1131 deluxe sedan', 'peugeot 504', 'audi 100 ls',
       'saab 99e', 'bmw 2002', 'amc gremlin', 'ford f250', 'chevy c20',
       'dodge d200', 'hi 1200d', 'chevrolet vega 2300', 'toyota corona',
       'ford pinto', 'plymouth satellite custom', 'ford torino 500',
       'amc matador', 'pontiac catalina brougham', 'dodge monaco (sw)',
       'ford country squire (sw)', 'pontiac safari (sw)',
       'amc hornet sportabout (sw)', 'chevrolet vega (sw)',
       'pontiac firebird', 'ford mustang', 'mercury capri 2000',
       'opel 1900', 'peugeot 304', 'fiat 124b', 'toyota corolla 1200',
       'datsun 1200', 'volkswagen model 111', 'plymouth cricket',
       'toyota corona hardtop', 'dodge colt hardtop', 'volkswagen type 3',
       'chevrolet vega', 'ford pinto runabout', 'amc ambassador sst',
       'mercury marquis', 'buick lesabre custom',
       'oldsmobile delta 88 royale', 'chrysler newport royal',
       'mazda rx2 coupe', 'amc matador (sw)',
       'chevrolet chevelle concours (sw)', 'ford gran torino (sw)',
       'plymouth satellite custom (sw)', 'volvo 145e (sw)',
       'volkswagen 411 (sw)', 'peugeot 504 (sw)', 'renault 12 (sw)',
       'ford pinto (sw)', 'datsun 510 (sw)',
       'toyouta corona mark ii (sw)', 'dodge colt (sw)',
       'toyota corolla 1600 (sw)', 'buick century 350',
       'chevrolet malibu', 'ford gran torino', 'dodge coronet custom',
       'mercury marquis brougham', 'chevrolet caprice classic',
       'ford ltd', 'plymouth fury gran sedan',
       'chrysler new yorker brougham', 'buick electra 225 custom',
       'amc ambassador brougham', 'plymouth valiant',
       'chevrolet nova custom', 'volkswagen super beetle', 'ford country',
       'plymouth custom suburb', 'oldsmobile vista cruiser',
       'toyota carina', 'datsun 610', 'maxda rx3', 'mercury capri v6',
       'fiat 124 sport coupe', 'chevrolet monte carlo s',
       'pontiac grand prix', 'fiat 128', 'opel manta', 'audi 100ls',
       'volvo 144ea', 'dodge dart custom', 'saab 99le', 'toyota mark ii',
       'oldsmobile omega', 'chevrolet nova', 'datsun b210',
       'chevrolet chevelle malibu classic', 'plymouth satellite sebring',
       'buick century luxus (sw)', 'dodge coronet custom (sw)',
       'audi fox', 'volkswagen dasher', 'datsun 710', 'dodge colt',
       'fiat 124 tc', 'honda civic', 'subaru', 'fiat x1.9',
       'plymouth valiant custom', 'mercury monarch', 'chevrolet bel air',
       'plymouth grand fury', 'buick century',
       'chevroelt chevelle malibu', 'plymouth fury', 'buick skyhawk',
       'chevrolet monza 2+2', 'ford mustang ii', 'toyota corolla',
       'pontiac astro', 'volkswagen rabbit', 'amc pacer', 'volvo 244dl',
       'honda civic cvcc', 'fiat 131', 'capri ii', 'renault 12tl',
       'dodge coronet brougham', 'chevrolet chevette', 'chevrolet woody',
       'vw rabbit', 'dodge aspen se', 'ford granada ghia',
       'pontiac ventura sj', 'amc pacer d/l', 'datsun b-210', 'volvo 245',
       'plymouth volare premier v8', 'mercedes-benz 280s',
       'cadillac seville', 'chevy c10', 'ford f108', 'dodge d100',
       'honda accord cvcc', 'buick opel isuzu deluxe', 'renault 5 gtl',
       'plymouth arrow gs', 'datsun f-10 hatchback',
       'oldsmobile cutlass supreme', 'dodge monaco brougham',
       'mercury cougar brougham', 'chevrolet concours', 'buick skylark',
       'plymouth volare custom', 'ford granada', 'pontiac grand prix lj',
       'chevrolet monte carlo landau', 'chrysler cordoba',
       'ford thunderbird', 'volkswagen rabbit custom',
       'pontiac sunbird coupe', 'toyota corolla liftback',
       'ford mustang ii 2+2', 'dodge colt m/m', 'subaru dl', 'datsun 810',
       'bmw 320i', 'mazda rx-4', 'volkswagen rabbit custom diesel',
       'ford fiesta', 'mazda glc deluxe', 'datsun b210 gx',
       'oldsmobile cutlass salon brougham', 'dodge diplomat',
       'mercury monarch ghia', 'pontiac phoenix lj',
       'ford fairmont (auto)', 'ford fairmont (man)', 'plymouth volare',
       'amc concord', 'buick century special', 'mercury zephyr',
       'dodge aspen', 'amc concord d/l',
       'buick regal sport coupe (turbo)', 'ford futura',
       'dodge magnum xe', 'datsun 510', 'dodge omni',
       'toyota celica gt liftback', 'plymouth sapporo',
       'oldsmobile starfire sx', 'datsun 200-sx', 'audi 5000',
       'volvo 264gl', 'saab 99gle', 'peugeot 604sl',
       'volkswagen scirocco', 'honda accord lx', 'pontiac lemans v6',
       'mercury zephyr 6', 'ford fairmont 4', 'amc concord dl 6',
       'dodge aspen 6', 'ford ltd landau', 'mercury grand marquis',
       'dodge st. regis', 'chevrolet malibu classic (sw)',
       'chrysler lebaron town @ country (sw)', 'vw rabbit custom',
       'maxda glc deluxe', 'dodge colt hatchback custom', 'amc spirit dl',
       'mercedes benz 300d', 'cadillac eldorado', 'plymouth horizon',
       'plymouth horizon tc3', 'datsun 210', 'fiat strada custom',
       'buick skylark limited', 'chevrolet citation',
       'oldsmobile omega brougham', 'pontiac phoenix',
       'toyota corolla tercel', 'datsun 310', 'ford fairmont',
       'audi 4000', 'toyota corona liftback', 'mazda 626',
       'datsun 510 hatchback', 'mazda glc', 'vw rabbit c (diesel)',
       'vw dasher (diesel)', 'audi 5000s (diesel)', 'mercedes-benz 240d',
       'honda civic 1500 gl', 'renault lecar deluxe', 'vokswagen rabbit',
       'datsun 280-zx', 'mazda rx-7 gs', 'triumph tr7 coupe',
       'ford mustang cobra', 'honda accord', 'plymouth reliant',
       'dodge aries wagon (sw)', 'toyota starlet', 'plymouth champ',
       'honda civic 1300', 'datsun 210 mpg', 'toyota tercel',
       'mazda glc 4', 'plymouth horizon 4', 'ford escort 4w',
       'ford escort 2h', 'volkswagen jetta', 'renault 18i',
       'honda prelude', 'datsun 200sx', 'peugeot 505s turbo diesel',
       'volvo diesel', 'toyota cressida', 'datsun 810 maxima',
       'oldsmobile cutlass ls', 'ford granada gl',
       'chrysler lebaron salon', 'chevrolet cavalier',
       'chevrolet cavalier wagon', 'chevrolet cavalier 2-door',
       'pontiac j2000 se hatchback', 'dodge aries se',
       'ford fairmont futura', 'amc concord dl', 'volkswagen rabbit l',
       'mazda glc custom l', 'mazda glc custom', 'plymouth horizon miser',
       'mercury lynx l', 'nissan stanza xe', 'honda civic (auto)',
       'datsun 310 gx', 'buick century limited',
       'oldsmobile cutlass ciera (diesel)', 'chrysler lebaron medallion',
       'ford granada l', 'toyota celica gt', 'dodge charger 2.2',
       'chevrolet camaro', 'ford mustang gl', 'vw pickup',
       'dodge rampage', 'ford ranger', 'chevy s-10'], dtype=object)

In [28]:
df['car name'].value_counts()

ford pinto          6
ford maverick       5
amc matador         5
toyota corolla      5
amc gremlin         4
                   ..
vw rabbit custom    1
volvo 245           1
toyota carina       1
amc pacer d/l       1
ford fairmont       1
Name: car name, Length: 305, dtype: int64

In [29]:
df['car name'].value_counts(ascending=True)

ford fairmont       1
amc pacer d/l       1
toyota carina       1
volvo 245           1
vw rabbit custom    1
                   ..
amc gremlin         4
toyota corolla      5
amc matador         5
ford maverick       5
ford pinto          6
Name: car name, Length: 305, dtype: int64

In [30]:
df['car name'].value_counts(ascending=False)

ford pinto          6
ford maverick       5
amc matador         5
toyota corolla      5
amc gremlin         4
                   ..
vw rabbit custom    1
volvo 245           1
toyota carina       1
amc pacer d/l       1
ford fairmont       1
Name: car name, Length: 305, dtype: int64