In [124]:
import pandas as pd
import numpy as np
df=pd.read_csv('titanic.csv')

# Data Cleaning

In [19]:
print("Is Null and isna")
print(df.isnull())
print("---------------------------------------------------------------------------------------------------")

print(df.isna())
print("---------------------------------------------------------------------------------------------------")

print(df.isnull().sum())
print("---------------------------------------------------------------------------------------------------")

      pclass   name    sex    age  sibsp  parch  ticket   fare  cabin  \
0      False  False  False  False  False  False   False  False  False
1      False  False  False  False  False  False   False  False  False
2      False  False  False  False  False  False   False  False  False
3      False  False  False  False  False  False   False  False  False
4      False  False  False  False  False  False   False  False  False
...      ...    ...    ...    ...    ...    ...     ...    ...    ...
1304   False  False  False  False  False  False   False  False   True
1305   False  False  False   True  False  False   False  False   True
1306   False  False  False  False  False  False   False  False   True
1307   False  False  False  False  False  False   False  False   True
1308   False  False  False  False  False  False   False  False   True

      embarked  survived
0        False     False
1        False     False
2        False     False
3        False     False
4        False     False
...        ...       ...
1304     False     False
1305     False     False
1306     False     False
1307     False     False
1308     False     False

[1309 rows x 11 columns]
---------------------------------------------------------------------------------------------------
      pclass   name    sex    age  sibsp  parch  ticket   fare  cabin  \
0      False  False  False  False  False  False   False  False  False
1      False  False  False  False  False  False   False  False  False
2      False  False  False  False  False  False   False  False  False
3      False  False  False  False  False  False   False  False  False
4      False  False  False  False  False  False   False  False  False
...      ...    ...    ...    ...    ...    ...     ...    ...    ...
1304   False  False  False  False  False  False   False  False   True
1305   False  False  False   True  False  False   False  False   True
1306   False  False  False  False  False  False   False  False   True
1307   False  False  False  False  False  False   False  False   True
1308   False  False  False  False  False  False   False  False   True

      embarked  survived
0        False     False
1        False     False
2        False     False
3        False     False
4        False     False
...        ...       ...
1304     False     False
1305     False     False
1306     False     False
1307     False     False
1308     False     False

[1309 rows x 11 columns]
---------------------------------------------------------------------------------------------------
pclass         0
name           0
sex            0
age          263
sibsp          0
parch          0
ticket         0
fare           1
cabin       1014
embarked       2
survived       0
dtype: int64
---------------------------------------------------------------------------------------------------

In [24]:
#fillna
#using constants
# using mean,median,mode
# using backward bfill and forward ffill
print("---------------------------------------------------------------------------------------------------------------")
print(df.fillna('130'))
print("---------------------------------------------------------------------------------------------------------------")
df=df.fillna(df.mean())
print(df)

---------------------------------------------------------------------------------------------------------------
      pclass                                             name     sex  \
0          1                    Allen, Miss. Elisabeth Walton  female
1          1                   Allison, Master. Hudson Trevor    male
2          1                     Allison, Miss. Helen Loraine  female
3          1             Allison, Mr. Hudson Joshua Creighton    male
4          1  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female
...      ...                                              ...     ...
1304       3                             Zabour, Miss. Hileni  female
1305       3                            Zabour, Miss. Thamine  female
1306       3                        Zakarian, Mr. Mapriededer    male
1307       3                              Zakarian, Mr. Ortin    male
1308       3                               Zimmerman, Mr. Leo    male

            age  sibsp  parch  ticket      fare    cabin embarked  survived
0     29.000000      0      0   24160  211.3375       B5        S         1
1      0.916700      1      2  113781  151.5500  C22 C26        S         1
2      2.000000      1      2  113781  151.5500  C22 C26        S         0
3     30.000000      1      2  113781  151.5500  C22 C26        S         0
4     25.000000      1      2  113781  151.5500  C22 C26        S         0
...         ...    ...    ...     ...       ...      ...      ...       ...
1304  14.500000      1      0    2665   14.4542      130        C         0
1305  29.881135      1      0    2665   14.4542      130        C         0
1306  26.500000      0      0    2656    7.2250      130        C         0
1307  27.000000      0      0    2670    7.2250      130        C         0
1308  29.000000      0      0  315082    7.8750      130        S         0

[1309 rows x 11 columns]
---------------------------------------------------------------------------------------------------------------
      pclass                                             name     sex  \
0          1                    Allen, Miss. Elisabeth Walton  female
1          1                   Allison, Master. Hudson Trevor    male
2          1                     Allison, Miss. Helen Loraine  female
3          1             Allison, Mr. Hudson Joshua Creighton    male
4          1  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female
...      ...                                              ...     ...
1304       3                             Zabour, Miss. Hileni  female
1305       3                            Zabour, Miss. Thamine  female
1306       3                        Zakarian, Mr. Mapriededer    male
1307       3                              Zakarian, Mr. Ortin    male
1308       3                               Zimmerman, Mr. Leo    male

            age  sibsp  parch  ticket      fare    cabin embarked  survived
0     29.000000      0      0   24160  211.3375       B5        S         1
1      0.916700      1      2  113781  151.5500  C22 C26        S         1
2      2.000000      1      2  113781  151.5500  C22 C26        S         0
3     30.000000      1      2  113781  151.5500  C22 C26        S         0
4     25.000000      1      2  113781  151.5500  C22 C26        S         0
...         ...    ...    ...     ...       ...      ...      ...       ...
1304  14.500000      1      0    2665   14.4542      NaN        C         0
1305  29.881135      1      0    2665   14.4542      NaN        C         0
1306  26.500000      0      0    2656    7.2250      NaN        C         0
1307  27.000000      0      0    2670    7.2250      NaN        C         0
1308  29.000000      0      0  315082    7.8750      NaN        S         0

[1309 rows x 11 columns]

In [115]:
data={
    'Id':[1,2,3,4,4],
    'Name':['Amit','Priya',np.nan,'Rahul',np.nan],
    'Marks':[80,np.nan,75,85,np.nan],
    'City':['Ahmedabad','rajkot',np.nan,'surat','Rajkot']
}
df=pd.DataFrame(data)

print("-----------------------------------------------------------------------------------------------")
print(df)
print("--------------------------------------------")

-----------------------------------------------------------------------------------------------
   Id   Name  Marks       City
0   1   Amit   80.0  Ahmedabad
1   2  Priya    NaN     rajkot
2   3    NaN   75.0        NaN
3   4  Rahul   85.0      surat
4   4    NaN    NaN     Rajkot
--------------------------------------------

In [54]:
df=df.fillna(df.mode().iloc[0])
print(df)

   Id   Name  Marks       City
0   1   Amit   80.0  Ahmedabad
1   2  Priya   80.0     rajkot
2   3  Priya   75.0     rajkot
3   4  Rahul   85.0      surat
4   4  Rahul   85.0     Rajkot

In [47]:
df=df.median(numeric_only=True)
print(df)

Id        3.0
Marks    75.0
dtype: float64

In [57]:
df=df.fillna(method='ffill')
print(df)

   Id   Name  Marks       City
0   1   Amit   80.0  Ahmedabad
1   2  Priya   80.0     rajkot
2   3  Priya   75.0     rajkot
3   4  Rahul   85.0      surat
4   4  Rahul   85.0     Rajkot

In [59]:
df=df.fillna(method='bfill')
print(df)

   Id   Name  Marks       City
0   1   Amit   80.0  Ahmedabad
1   2  Priya   75.0     rajkot
2   3  Rahul   75.0      surat
3   4  Rahul   85.0      surat
4   4    NaN    NaN     Rajkot

# From titanic.csv file

In [73]:
df.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [74]:
df.tail()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
1304,3,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.8750,NaN,S,0

In [75]:
df.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [76]:
df.nunique()

pclass         3
name        1307
sex            2
age           98
sibsp          7
parch          8
ticket       929
fare         281
cabin        186
embarked       3
survived       2
dtype: int64

In [77]:
df.shape

(1309, 11)

In [68]:

df['sex'].unique()

array(['female', 'male'], dtype=object)

In [71]:
(df['sex']=='male').value_counts()

True     843
False    466
Name: sex, dtype: int64

In [78]:
df.shape[0]*100

130900

In [79]:
df.isnull().sum()

pclass         0
name           0
sex            0
age          263
sibsp          0
parch          0
ticket         0
fare           1
cabin       1014
embarked       2
survived       0
dtype: int64

In [92]:
print("---------------------------------------------------------------------------------------------------------------")
print(df.fillna('130'))
print("---------------------------------------------------------------------------------------------------------------")
df=df.fillna(df.mean())
print(df)
print(df.isnull().sum())

---------------------------------------------------------------------------------------------------------------
      pclass                                             name     sex  \
0          1                    Allen, Miss. Elisabeth Walton  female
1          1                   Allison, Master. Hudson Trevor    male
2          1                     Allison, Miss. Helen Loraine  female
3          1             Allison, Mr. Hudson Joshua Creighton    male
4          1  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female
...      ...                                              ...     ...
1304       3                             Zabour, Miss. Hileni  female
1305       3                            Zabour, Miss. Thamine  female
1306       3                        Zakarian, Mr. Mapriededer    male
1307       3                              Zakarian, Mr. Ortin    male
1308       3                               Zimmerman, Mr. Leo    male

            age  sibsp  parch  ticket      fare    cabin embarked  survived
0     29.000000      0      0   24160  211.3375       B5        S         1
1      0.916700      1      2  113781  151.5500  C22 C26        S         1
2      2.000000      1      2  113781  151.5500  C22 C26        S         0
3     30.000000      1      2  113781  151.5500  C22 C26        S         0
4     25.000000      1      2  113781  151.5500  C22 C26        S         0
...         ...    ...    ...     ...       ...      ...      ...       ...
1304  14.500000      1      0    2665   14.4542      130        C         0
1305  29.881135      1      0    2665   14.4542      130        C         0
1306  26.500000      0      0    2656    7.2250      130        C         0
1307  27.000000      0      0    2670    7.2250      130        C         0
1308  29.000000      0      0  315082    7.8750      130        S         0

[1309 rows x 11 columns]
---------------------------------------------------------------------------------------------------------------
      pclass                                             name     sex  \
0          1                    Allen, Miss. Elisabeth Walton  female
1          1                   Allison, Master. Hudson Trevor    male
2          1                     Allison, Miss. Helen Loraine  female
3          1             Allison, Mr. Hudson Joshua Creighton    male
4          1  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female
...      ...                                              ...     ...
1304       3                             Zabour, Miss. Hileni  female
1305       3                            Zabour, Miss. Thamine  female
1306       3                        Zakarian, Mr. Mapriededer    male
1307       3                              Zakarian, Mr. Ortin    male
1308       3                               Zimmerman, Mr. Leo    male

            age  sibsp  parch  ticket      fare    cabin embarked  survived
0     29.000000      0      0   24160  211.3375       B5        S         1
1      0.916700      1      2  113781  151.5500  C22 C26        S         1
2      2.000000      1      2  113781  151.5500  C22 C26        S         0
3     30.000000      1      2  113781  151.5500  C22 C26        S         0
4     25.000000      1      2  113781  151.5500  C22 C26        S         0
...         ...    ...    ...     ...       ...      ...      ...       ...
1304  14.500000      1      0    2665   14.4542      NaN        C         0
1305  29.881135      1      0    2665   14.4542      NaN        C         0
1306  26.500000      0      0    2656    7.2250      NaN        C         0
1307  27.000000      0      0    2670    7.2250      NaN        C         0
1308  29.000000      0      0  315082    7.8750      NaN        S         0

[1309 rows x 11 columns]
pclass         0
name           0
sex            0
age            0
sibsp          0
parch          0
ticket         0
fare           0
cabin       1014
embarked       2
survived       0
dtype: int64

In [90]:
df['age']=df['age'].fillna(df['age'].mean())
print(df.isnull().sum())#to see if the null values got filled or not

pclass         0
name           0
sex            0
age            0
sibsp          0
parch          0
ticket         0
fare           1
cabin       1014
embarked       2
survived       0
dtype: int64

In [91]:
df['fare']=df['fare'].fillna(df['fare'].median())
print(df.isnull().sum())

pclass         0
name           0
sex            0
age            0
sibsp          0
parch          0
ticket         0
fare           0
cabin       1014
embarked       2
survived       0
dtype: int64

In [93]:
df['embarked']=df['embarked'].fillna(df['embarked'].mode()[0])
print(df.isnull().sum())

pclass         0
name           0
sex            0
age            0
sibsp          0
parch          0
ticket         0
fare           0
cabin       1014
embarked       0
survived       0
dtype: int64

In [94]:
df['cabin']=df['cabin'].fillna(method='bfill')
print(df.isnull().sum())

pclass       0
name         0
sex          0
age          0
sibsp        0
parch        0
ticket       0
fare         0
cabin       59
embarked     0
survived     0
dtype: int64

In [98]:
#From our dataset
print(df)
print("----------------------------------------------------")
df=df.dropna()
print(df)
print("------------------------------------------------------")

   Id   Name  Marks       City
0   1   Amit   80.0  Ahmedabad
1   2  Priya    NaN     rajkot
2   3    NaN   75.0        NaN
3   4  Rahul   85.0      surat
4   4    NaN    NaN     Rajkot
----------------------------------------------------
   Id   Name  Marks       City
0   1   Amit   80.0  Ahmedabad
3   4  Rahul   85.0      surat
------------------------------------------------------

In [102]:
#It will drop any row or column if has nan
df=df.dropna(how='any')
print(df)

   Id   Name  Marks       City
0   1   Amit   80.0  Ahmedabad
3   4  Rahul   85.0      surat

In [104]:
df=df.dropna(how='all')
print(df)

   Id   Name  Marks       City
0   1   Amit   80.0  Ahmedabad
1   2  Priya    NaN     rajkot
2   3    NaN   75.0        NaN
3   4  Rahul   85.0      surat
4   4    NaN    NaN     Rajkot

In [107]:
df=df.dropna(how='any',axis=1)
print(df)

   Id
0   1
1   2
2   3
3   4
4   4

In [111]:
#all will only drop if whole row(axis=0) or columns(axis=1) value is null
df=df.dropna(how='all',axis=1)
print(df)

   Id   Name  Marks       City
0   1   Amit   80.0  Ahmedabad
1   2  Priya    NaN     rajkot
2   3    NaN   75.0        NaN
3   4  Rahul   85.0      surat
4   4    NaN    NaN     Rajkot

In [114]:
df.dropna(subset=['Marks'])

   Id   Name  Marks       City
0   1   Amit   80.0  Ahmedabad
2   3    NaN   75.0        NaN
3   4  Rahul   85.0      surat

In [116]:
# non-null>=thresh-value then keep
# non-null<thresh-value then drop

df.dropna(thresh=2)

   Id   Name  Marks       City
0   1   Amit   80.0  Ahmedabad
1   2  Priya    NaN     rajkot
2   3    NaN   75.0        NaN
3   4  Rahul   85.0      surat
4   4    NaN    NaN     Rajkot

In [120]:
df.dropna(thresh=3)

   Id   Name  Marks       City
0   1   Amit   80.0  Ahmedabad
1   2  Priya    NaN     rajkot
3   4  Rahul   85.0      surat

In [121]:
df.isnull().sum()

Id       0
Name     2
Marks    2
City     1
dtype: int64

In [129]:
import pandas as pd
import numpy as np
df=pd.read_csv('titanic.csv')
df=df.drop(index=[0,2])
print(df)

      pclass                                             name     sex  \
1          1                   Allison, Master. Hudson Trevor    male
3          1             Allison, Mr. Hudson Joshua Creighton    male
4          1  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female
5          1                              Anderson, Mr. Harry    male
6          1                Andrews, Miss. Kornelia Theodosia  female
...      ...                                              ...     ...
1304       3                             Zabour, Miss. Hileni  female
1305       3                            Zabour, Miss. Thamine  female
1306       3                        Zakarian, Mr. Mapriededer    male
1307       3                              Zakarian, Mr. Ortin    male
1308       3                               Zimmerman, Mr. Leo    male

          age  sibsp  parch  ticket      fare    cabin embarked  survived
1      0.9167      1      2  113781  151.5500  C22 C26        S         1
3     30.0000      1      2  113781  151.5500  C22 C26        S         0
4     25.0000      1      2  113781  151.5500  C22 C26        S         0
5     48.0000      0      0   19952   26.5500      E12        S         1
6     63.0000      1      0   13502   77.9583       D7        S         1
...       ...    ...    ...     ...       ...      ...      ...       ...
1304  14.5000      1      0    2665   14.4542      NaN        C         0
1305      NaN      1      0    2665   14.4542      NaN        C         0
1306  26.5000      0      0    2656    7.2250      NaN        C         0
1307  27.0000      0      0    2670    7.2250      NaN        C         0
1308  29.0000      0      0  315082    7.8750      NaN        S         0

[1307 rows x 11 columns]

In [131]:
import pandas as pd
import numpy as np
df=pd.read_csv('titanic.csv')


df=df.drop(columns='age')
print(df)

      pclass                                             name     sex  sibsp  \
0          1                    Allen, Miss. Elisabeth Walton  female      0
1          1                   Allison, Master. Hudson Trevor    male      1
2          1                     Allison, Miss. Helen Loraine  female      1
3          1             Allison, Mr. Hudson Joshua Creighton    male      1
4          1  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female      1
...      ...                                              ...     ...    ...
1304       3                             Zabour, Miss. Hileni  female      1
1305       3                            Zabour, Miss. Thamine  female      1
1306       3                        Zakarian, Mr. Mapriededer    male      0
1307       3                              Zakarian, Mr. Ortin    male      0
1308       3                               Zimmerman, Mr. Leo    male      0

      parch  ticket      fare    cabin embarked  survived
0         0   24160  211.3375       B5        S         1
1         2  113781  151.5500  C22 C26        S         1
2         2  113781  151.5500  C22 C26        S         0
3         2  113781  151.5500  C22 C26        S         0
4         2  113781  151.5500  C22 C26        S         0
...     ...     ...       ...      ...      ...       ...
1304      0    2665   14.4542      NaN        C         0
1305      0    2665   14.4542      NaN        C         0
1306      0    2656    7.2250      NaN        C         0
1307      0    2670    7.2250      NaN        C         0
1308      0  315082    7.8750      NaN        S         0

[1309 rows x 10 columns]

In [134]:
import pandas as pd
import numpy as np
df=pd.read_csv('titanic.csv')
df=df.drop("Gender",axis=1)
print(df)

KeyError: "['Gender'] not found in axis"