In [1]:
import pandas as pd

In [2]:
df=pd.DataFrame({'name':['A','B','C','D','E'],'Department':['cs','it','ec','cs','it']})
df_encode=pd.get_dummies(df,columns=['Department'])
df_encode

  name  Department_cs  Department_ec  Department_it
0    A           True          False          False
1    B          False          False           True
2    C          False           True          False
3    D           True          False          False
4    E          False          False           True

In [3]:
df=pd.DataFrame({'name':['A','B','C','D','E'],'Department':['cs','it','ec','cs','it']})
df_encode=pd.get_dummies(df,columns=['Department'],drop_first=True)
df_encode

  name  Department_ec  Department_it
0    A          False          False
1    B          False           True
2    C           True          False
3    D          False          False
4    E          False           True

In [4]:
import numpy as np
df=pd.DataFrame({'name':['A','B','C','D','E'],'Department':['cs','it','ec','cs','it'],'score':[60,45,78,90,34]})
df['Grade']=np.where(df['score']>60,'A',np.where(df['score']>40,'B','C'))
df

  name Department  score Grade
0    A         cs     60     B
1    B         it     45     B
2    C         ec     78     A
3    D         cs     90     A
4    E         it     34     C

In [7]:
from sklearn.model_selection import train_test_split
df=pd.DataFrame({'Hours':[1,2,3,4,5],'score':[10,45,34,67,80]})
print(df)
x=df[['Hours']]
y=df[['score']]
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=42)
print(x_train)
print(x_test)

   Hours  score
0      1     10
1      2     45
2      3     34
3      4     67
4      5     80
   Hours
4      5
2      3
0      1
3      4
   Hours
1      2

In [8]:
from sklearn.model_selection import train_test_split
df=pd.DataFrame({'Hours':[1,2,3,4,5],'score':[10,45,34,67,80]})
print(df)
x=df[['Hours']]
y=df[['score']]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.8,random_state=42)
print(x_train)
print(x_test)

   Hours  score
0      1     10
1      2     45
2      3     34
3      4     67
4      5     80
   Hours
3      4
   Hours
1      2
4      5
2      3
0      1

In [9]:
s1=pd.Series([1,2,3,4,5])
s2=pd.Series([10,20,30,40,50])
print(s1+s2)
print(s1.add(s2))

0    11
1    22
2    33
3    44
4    55
dtype: int64
0    11
1    22
2    33
3    44
4    55
dtype: int64